name: backend_linter

on:
  pull_request:
    branches:
      - '*'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check
        if: always()
        run: |
          ruff check .

      - name: Run ruff format check
        if: always()
        run: |
          ruff format --diff