name: backend_tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        working-directory: frontend/app
        run: |
          pip install -e .
          pip install -r tests/requirements.txt

      - name: Run pytest
        working-directory: frontend/app
        if: always()
        run: |
          pytest tests
