name: Biome Check on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run biome check
        if: always()
        run: |
          cd frontend/app
          pnpm install
          pnpm biome check
