name: frontend_linter

on:
  pull_request:
    branches:
      - '*'

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: biomejs/setup-biome@v2
        with:
          version: latest

      - run: biome ci .