name: frontend_tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4

#      - uses: pnpm/action-setup@v4
#        with:
#          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: frontend/app/pnpm-lock.yaml
          cache: 'pnpm'

      - working-directory: frontend/app
        run: pnpm install

      - working-directory: frontend/app
        run: pnpm test
