name: frontend_tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  vitest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
#      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: frontend/app/package-lock.json
          cache: 'npm'

#      - name: Install dependencies
      - working-directory: frontend/app
        run: npm install

#      - name: Run tests
      - working-directory: frontend/app
        run: npm test
