name: Ruff Check on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check
        run: |
          ruff check .

      - name: Run ruff format check
        continue-on-error: true  # Run this even if previous steps fail
        run: |
          ruff format --diff